// Code generated by "stringer -type=controlMsg"; DO NOT EDIT.

package component

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EnablePeerMessaging-0]
	_ = x[DisablePeerMessaging-1]
	_ = x[Shutdown-2]
	_ = x[ShutdownAfter-3]
	_ = x[Cancel-4]
	_ = x[CancelAfter-5]
}

const _controlMsg_name = "EnablePeerMessagingDisablePeerMessagingShutdownShutdownAfterCancelCancelAfter"

var _controlMsg_index = [...]uint8{0, 19, 39, 47, 60, 66, 77}

func (i controlMsg) String() string {
	if i < 0 || i >= controlMsg(len(_controlMsg_index)-1) {
		return "controlMsg(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _controlMsg_name[_controlMsg_index[i]:_controlMsg_index[i+1]]
}
